[package]
name = "peter-commander"
version = "0.3.0"
edition = "2024"
description = "A terminal file manager"
license = "MIT"
repository = "https://github.com/piotrsrodka/peter-commander"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
crossterm = "0.29.0"
dirs = "7.0.0"
ratatui = "0.30.2"
shell-words = "1.1.1"
signal-hook = "0.4.4"
